# Form implementation generated from reading ui file 'd:\Projects\PyQt-Fluent-Widgets\about.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon

from src.common.config import Config


class AboutWidget(QtWidgets.QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumWidth(800)
        Form.setMinimumHeight(600)
        self.label_1 = QtWidgets.QLabel(parent=Form)
        self.label_1.setGeometry(QtCore.QRect(100, 150, 600, 100))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(100, 250, 600, 100))
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(730, 500, 50, 20))
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(630, 500, 50, 20))
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        window_icon = Config.ICON_PATH + "about.ico"
        Form.setWindowIcon(QIcon(window_icon))
        Form.setWindowTitle(_translate("Form", "About ThreeWords"))
        self.label_1.setText(_translate("Form", "这可能是个总是说废话的程序"))
        self.label_2.setText(_translate("Form", "不过或许也有人喜欢呢，哈哈哈"))
        self.label_3.setText(
            _translate(
                "Form",
                """<a style="font-family: Microsoft YaHei UI; color: #1976c6; font-size: 10pt;  text-decoration: none" href="https://hitokoto.cn/">鸣谢</a>""",
            )
        )
        self.label_3.setOpenExternalLinks(True)
        self.label_4.setText(
            _translate(
                "Form",
                """<a style="font-family: Microsoft YaHei UI; color: #1976c6; font-size: 10pt;  text-decoration: none" href="https://github.com/BeingFun/ThreeWords"> GitHub</a>""",
            )
        )
        self.label_4.setOpenExternalLinks(True)
